// src/react-legacy/src/components/menuComponents/CustomButtons.tsx
import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faSpinner, IconDefinition } from "@fortawesome/free-solid-svg-icons"; // Example icon import
import "./CustomButtons.css"; // Import CSS file for styling

// Define the type for each button object in the array
export interface CustomButton {
  action: () => void;
  show: boolean;
  backgroundColor?: string;
  disabled?: boolean;
  icon?: IconDefinition; // FontAwesome icons are typed as IconDefinition
  iconStyle?: React.CSSProperties;
  text?: string;
  textStyle?: React.CSSProperties;
  customComponent?: React.ReactNode;
}

// Define the prop type using an interface
export interface CustomButtonsOptions {
  buttons: CustomButton[];
}

export type CustomButtonsType = (options: CustomButtonsOptions) => React.JSX.Element;

/**
 * CustomButtons component renders a list of customizable buttons.
 *
 * @component
 * @param {CustomButtonsOptions} props - The properties for the CustomButtons component.
 * @param {Array} props.buttons - An array of button configurations.
 * @param {Function} props.buttons[].action - The function to be called when the button is clicked.
 * @param {boolean} props.buttons[].show - Determines if the button should be displayed.
 * @param {string} props.buttons[].backgroundColor - The background color of the button.
 * @param {boolean} props.buttons[].disabled - Determines if the button should be disabled.
 * @param {IconDefinition} [props.buttons[].icon] - The icon to be displayed on the button.
 * @param {Object} [props.buttons[].iconStyle] - The style to be applied to the icon.
 * @param {string} [props.buttons[].text] - The text to be displayed on the button.
 * @param {Object} [props.buttons[].textStyle] - The style to be applied to the text.
 * @param {React.ReactNode} [props.buttons[].customComponent] - A custom component to be rendered inside the button.
 *
 * @returns {React.JSX.Element} The rendered CustomButtons component.
 * 
 * @example
 * ```tsx
 * import React from 'react';
 * import { CustomButtons } from 'mediasfu-reactjs';
 * import { faSpinner, faCheck } from '@fortawesome/free-solid-svg-icons';
 * 
 * const buttons = [
 *   {
 *     action: () => console.log("Save clicked"),
 *     show: true,
 *     backgroundColor: "green",
 *     disabled: false,
 *     icon: faCheck,
 *     iconStyle: { color: "white" },
 *     text: "Save",
 *     textStyle: { color: "white", fontSize: "16px" },
 *   },
 *   {
 *     action: () => console.log("Loading..."),
 *     show: true,
 *     backgroundColor: "gray",
 *     disabled: true,
 *     icon: faSpinner,
 *     iconStyle: { color: "lightgray" },
 *     text: "Loading",
 *     textStyle: { color: "lightgray", fontSize: "16px" },
 *     customComponent: <CustomSpinner />, // Example custom component
 *   },
 * ];
 * 
 * const App = () => (
 *   <CustomButtons buttons={buttons} />
 * );
 * 
 * export default App;
 * ```
 */


const CustomButtons: React.FC<CustomButtonsOptions> = ({ buttons }) => {
  return (
    <div className="mediasfu-customButtonsContainer">
      {buttons.map((button, index) => (
        <button
          key={index}
          onClick={() => {
            button.action();
          }}
          className="customButton"
          style={{
            backgroundColor: button.show
              ? button.backgroundColor
              : "transparent",
            display: button.show ? "flex" : "none",
          }}
          disabled={button.disabled}
        >
          <div className="buttonContent">
            {button.icon ? (
              <>
                <FontAwesomeIcon
                  icon={button.icon}
                  style={{ ...styles.customButtonIcon, ...button.iconStyle }}
                />
                {button.text && (
                  <span className="customButtonText" style={button.textStyle}>
                    {button.text}
                  </span>
                )}
              </>
            ) : button.customComponent ? (
              button.customComponent
            ) : (
              <FontAwesomeIcon icon={faSpinner} spin /> // Example placeholder for loading icon
            )}
          </div>
        </button>
      ))}
    </div>
  );
};

const styles = {
  customButtonIcon: {
    fontSize: 20,
    marginRight: 5,
  },
};

export default CustomButtons;

// src/components/menuComponents/CustomButtons.vue
<!--
/**
 * @fileoverview CustomButtons - Flexible custom button container
 * @component CustomButtons
 * @module components/menuComponents/CustomButtons
 * 
 * @description
 * A simple, flexible container for rendering custom action buttons. Each button can
 * display an icon, text label, or fully custom Vue component. Supports conditional
 * visibility, disabled states, and custom styling per button. Used for injecting
 * custom actions into menus, toolbars, and control panels.
 * 
 * Features:
 * - FontAwesome icon support with custom sizing/styling
 * - Optional text labels alongside icons
 * - Custom Vue component injection per button
 * - Conditional visibility via show prop
 * - Disabled state support
 * - Custom background colors per button
 * - Fallback spinner for loading states
 * - Flexible layout via CSS (horizontal/vertical)
 * 
 * @example Basic Icon Buttons
 * // <CustomButtons
 *   // :buttons="[
 *     {
 *       icon: faGear,
 *       text: 'Settings',
 *       show: true,
 *       disabled: false,
 *       backgroundColor: '#007bff',
 *       action: () => openSettings()
 *     },
 *     {
 *       icon: faSignOutAlt,
 *       text: 'Leave',
 *       show: true,
 *       disabled: false,
 *       backgroundColor: '#dc3545',
 *       action: () => leaveRoom()
 *     }
 *   ]"
 * // />
 * 
 * @example With Custom Component
 * // <CustomButtons
 *   // :buttons="[
 *     {
 *       customComponent: MyCustomButton,
 *       show: true,
 *       action: () => handleCustomAction()
 *     }
 *   ]"
 * // />
 * 
 * @example Loading State (No Icon)
 * // <CustomButtons
 *   // :buttons="[
 *     {
 *       text: 'Loading...',
 *       show: true,
 *       disabled: true,
 *       action: () => {}
 *     }
 *   ]"
 * // />
 * 
 * @remarks
 * This component is intentionally simple - it's a pure renderer for button data.
 * All logic (click handlers, visibility, styling) is defined in the buttons array.
 * When no icon or customComponent is provided, a spinner is shown as a fallback.
 * 
 * Workflow:
 * 1. Receives buttons array via props
 * 2. Renders each button with conditional display based on show prop
 * 3. Applies custom backgroundColor when visible, transparent when hidden
 * 4. Shows icon + text, customComponent, or fallback spinner
 * 5. Calls button.action on click
 * 6. Respects disabled state
 * 
 * @see {@link MenuModal} - Uses CustomButtons for custom menu actions
 * @see {@link ControlButtonsComponent} - Alternative for standard control buttons
 */
-->
<template>
  <div class="mediasfu-customButtonsContainer">
    <button
      v-for="(button, index) in buttons"
      :key="index"
      class="customButton"
      :style="{
        backgroundColor: button.show ? button.backgroundColor : 'transparent',
        display: button.show ? 'flex' : 'none',
      }"
      :disabled="button.disabled"
      @click="button.action"
    >
      <div class="buttonContent">
        <template v-if="button.icon">
          <font-awesome-icon
            :icon="button.icon"
            :style="{ ...customButtonIconStyle, ...button.iconStyle }"
          />
          <span
            v-if="button.text"
            class="customButtonText"
            :style="button.textStyle"
          >
            {{ button.text }}
          </span>
        </template>
        <component
          :is="button.customComponent"
          v-else-if="button.customComponent"
        />
        <font-awesome-icon
          v-else
          :icon="faSpinner"
          spin
        />
      </div>
    </button>
  </div>
</template>

<script setup lang="ts">
import type { Component, CSSProperties } from 'vue';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import { faSpinner, type IconDefinition } from '@fortawesome/free-solid-svg-icons';

/**
 * Custom button definition
 * @interface CustomButton
 * 
 * @property {function} action - Click handler function
 * @property {boolean} show - Whether button is visible
 * @property {string} [backgroundColor] - Custom background color (e.g., '#007bff')
 * @property {boolean} [disabled] - Whether button is disabled
 * @property {IconDefinition} [icon] - FontAwesome icon definition
 * @property {CSSProperties} [iconStyle] - Custom icon styles
 * @property {string} [text] - Text label to display alongside icon
 * @property {CSSProperties} [textStyle] - Custom text styles
 * @property {Component} [customComponent] - Custom Vue component to render instead of icon
 * 
 * @example
 * ```typescript
 * const button: CustomButton = {
 *   // icon: faGear,
 *   // text: 'Settings',
 *   // show: true,
 *   // disabled: false,
 *   // backgroundColor: '#007bff',
 *   // action: () => openSettings()
 * }
 * ```
 */
export interface CustomButton {
  action: () => void;
  show: boolean;
  backgroundColor?: string;
  disabled?: boolean;
  icon?: IconDefinition;
  iconStyle?: CSSProperties;
  text?: string;
  textStyle?: CSSProperties;
  customComponent?: Component;
}

export interface CustomButtonsProps {
  buttons: CustomButton[];
}

defineProps<CustomButtonsProps>();

const customButtonIconStyle: CSSProperties = {
  fontSize: '20px',
  marginRight: '5px',
};
</script>

<style scoped>
@import './CustomButtons.css';
</style>
