// src/methods/utils/MiniAudioPlayer/MiniAudioPlayer.vue
<template>
  <div :style="containerStyle">
    <audio
      v-if="streamRef"
      ref="audioRef"
      autoplay
      playsinline
    />
    <component
      :is="resolvedMiniAudioComponent"
      v-if="showMiniAudio && resolvedMiniAudioComponent"
      v-bind="resolvedMiniAudioProps"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onBeforeUnmount, nextTick, type CSSProperties, type Component } from 'vue';
import MiniAudio from '../../../components/displayComponents/MiniAudio.vue';
import type { Consumer } from 'mediasoup-client';
import type { BreakoutParticipant, Participant } from '../../../../../SharedTypes';

interface MiniAudioPlayerParameters {
  breakOutRoomStarted: boolean;
  breakOutRoomEnded: boolean;
  limitedBreakRoom: BreakoutParticipant[];
  reUpdateInter?: (options: Record<string, unknown>) => void | Promise<void>;
  updateParticipantAudioDecibels?: (options: Record<string, unknown>) => void;
  getUpdatedAllParams: () => MiniAudioPlayerParameters & Record<string, unknown>;
  updateActiveSounds?: (sounds: string[]) => void;
  miniAudioComponent?: Component;
  [key: string]: unknown;
}

export interface MiniAudioPlayerProps {
  stream: MediaStream | null;
  remoteProducerId: string;
  consumer: Consumer;
  parameters: MiniAudioPlayerParameters;
  miniAudioComponent?: Component | null;
  miniAudioProps?: Record<string, unknown>;
}

const props = withDefaults(defineProps<MiniAudioPlayerProps>(), {
  stream: null,
  miniAudioComponent: null,
  miniAudioProps: () => ({}),
});

const audioRef = ref<HTMLAudioElement | null>(null);
const showWaveModal = ref(false);
const isMuted = ref(false);
const autoWaveCheck = ref(false);

// Resolve miniAudioComponent from props or parameters
const parameterMiniAudioComponent = computed<Component | undefined>(
  () => props.parameters.miniAudioComponent as Component | undefined
);

const resolvedMiniAudioComponent = computed<Component | null>(
  () => props.miniAudioComponent ?? parameterMiniAudioComponent.value ?? MiniAudio
);

const resolvedMiniAudioProps = computed<Record<string, unknown>>(() => ({
  ...(props.miniAudioProps ?? {}),
  showWaveform: showWaveModal.value,
  visible: showWaveModal.value && !isMuted.value,
}));

const showMiniAudio = computed(() => showWaveModal.value && !isMuted.value && resolvedMiniAudioComponent.value);
const streamRef = computed(() => props.stream);

const containerStyle: CSSProperties = {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  zIndex: 9,
};

let intervalId: number | null = null;

const stopMonitoring = () => {
  if (intervalId !== null) {
    window.clearInterval(intervalId);
    intervalId = null;
  }
};

const setAudioSource = (stream: MediaStream | null) => {
  nextTick(() => {
    const element = audioRef.value;
    if (!element) {
      return;
    }
    element.srcObject = stream;
    if (stream) {
      const playPromise = element.play?.();
      if (playPromise instanceof Promise) {
        playPromise.catch(() => {
          /* ignore autoplay rejection */
        });
      }
    }
  });
};

const startMonitoring = () => {
  stopMonitoring();
  if (!props.stream) {
    return;
  }

  const baseParams = props.parameters;
  let consLow = false;

  intervalId = window.setInterval(async () => {
    let averageLoudness = 128;

    try {
      const receiver = props.consumer?.rtpReceiver;
      const stats = await receiver?.getStats?.();
      stats?.forEach((report) => {
        const stat = report as { type?: string; kind?: string; audioLevel?: number };
        if (stat.type === 'inbound-rtp' && stat.kind === 'audio' && typeof stat.audioLevel === 'number') {
          averageLoudness = 127.5 + stat.audioLevel * 127.5;
        }
      });
    } catch {
      /* stats unavailable */
    }

    const updatedParams = baseParams.getUpdatedAllParams?.() ?? baseParams;
    const {
      eventType,
      meetingDisplayType,
      shared,
      shareScreenStarted,
      dispActiveNames = [],
      adminNameStream: initialAdminNameStream,
      participants = [],
      activeSounds: activeSoundsRaw = [],
      autoWave = false,
      updateActiveSounds,
      paginatedStreams = [],
      currentUserPage = 0,
      reUpdateInter: updatedReUpdateInter,
      updateParticipantAudioDecibels: updatedUpdateParticipantAudioDecibels,
      breakOutRoomStarted: updatedBreakoutStarted,
      breakOutRoomEnded: updatedBreakoutEnded,
      limitedBreakRoom: updatedLimitedBreakRoom,
    } = updatedParams as MiniAudioPlayerParameters & Record<string, unknown>;

    const reUpdateInter = updatedReUpdateInter ?? baseParams.reUpdateInter;
    const updateParticipantAudioDecibels = updatedUpdateParticipantAudioDecibels ?? baseParams.updateParticipantAudioDecibels;
    const breakOutRoomStarted = updatedBreakoutStarted ?? baseParams.breakOutRoomStarted ?? false;
    const breakOutRoomEnded = updatedBreakoutEnded ?? baseParams.breakOutRoomEnded ?? false;
    const limitedBreakRoom = updatedLimitedBreakRoom ?? baseParams.limitedBreakRoom ?? [];

    const activeSounds = Array.isArray(activeSoundsRaw) ? [...activeSoundsRaw] : [];
    const autoWaveEnabled = typeof autoWave === 'boolean' ? autoWave : false;
    const paginatedList = Array.isArray(paginatedStreams) ? paginatedStreams : [];
    const pageIndex = typeof currentUserPage === 'number' ? currentUserPage : 0;
    const currentPage = Array.isArray(paginatedList[pageIndex])
      ? (paginatedList[pageIndex] as unknown[])
      : [];
    const displayedNames = Array.isArray(dispActiveNames) ? dispActiveNames : [];
    const participant = (participants as Participant[]).find((obj) => obj.audioID === props.remoteProducerId);

    let audioActiveInRoom = true;
    if (participant && breakOutRoomStarted && !breakOutRoomEnded) {
      const restrictedNames = new Set((limitedBreakRoom as BreakoutParticipant[]).map((obj) => obj.name));
      if (participant.name && !restrictedNames.has(participant.name)) {
        audioActiveInRoom = false;
      }
    }

    if (meetingDisplayType !== 'video') {
      autoWaveCheck.value = true;
    }
    if (shared || shareScreenStarted) {
      autoWaveCheck.value = false;
    }

    if (participant) {
      isMuted.value = participant.muted ?? false;

      if (eventType !== 'chat' && eventType !== 'broadcast') {
        updateParticipantAudioDecibels?.({
          name: participant.name ?? '',
          averageLoudness,
          audioDecibels: updatedParams.audioDecibels,
          updateAudioDecibels: updatedParams.updateAudioDecibels,
        });
      }

      let adminNameStream = initialAdminNameStream as string | undefined;
      const getEntryName = (entry: unknown): string | undefined => {
        if (entry && typeof entry === 'object' && 'name' in entry) {
          const value = (entry as { name?: unknown }).name;
          if (typeof value === 'string') {
            return value;
          }
        }
        return undefined;
      };

      const inPage = (currentPage as unknown[]).findIndex((entry) => getEntryName(entry) === participant.name);

      if (participant.name && !displayedNames.includes(participant.name) && inPage === -1) {
        autoWaveCheck.value = false;
        if (!adminNameStream) {
          const adminParticipant = (participants as Participant[]).find((obj) => obj.islevel === '2');
          adminNameStream = adminParticipant?.name ?? '';
        }
        if (participant.name === adminNameStream) {
          autoWaveCheck.value = true;
        }
      } else {
        autoWaveCheck.value = true;
      }

      if (
        participant.videoID ||
        autoWaveCheck.value ||
        (breakOutRoomStarted && !breakOutRoomEnded && audioActiveInRoom)
      ) {
        showWaveModal.value = false;

        if (averageLoudness > 127.5) {
          consLow = false;
          if (participant.name && !activeSounds.includes(participant.name)) {
            activeSounds.push(participant.name);
            if (!(shareScreenStarted || shared) || participant.videoID) {
              if (eventType !== 'chat' && eventType !== 'broadcast' && participant.name) {
                void reUpdateInter?.({
                  name: participant.name,
                  add: true,
                  average: averageLoudness,
                  parameters: updatedParams,
                });
              }
            }
          }
        } else {
          if (participant.name && activeSounds.includes(participant.name) && consLow) {
            activeSounds.splice(activeSounds.indexOf(participant.name), 1);
            if (!(shareScreenStarted || shared) || participant.videoID) {
              if (eventType !== 'chat' && eventType !== 'broadcast' && participant.name) {
                void reUpdateInter?.({
                  name: participant.name,
                  average: averageLoudness,
                  parameters: updatedParams,
                });
              }
            }
          } else {
            consLow = true;
          }
        }
      } else {
        if (averageLoudness > 127.5) {
          showWaveModal.value = autoWaveEnabled;
          if (participant.name && !activeSounds.includes(participant.name)) {
            activeSounds.push(participant.name);
          }
          if ((shareScreenStarted || shared) && !participant.videoID) {
            /* do nothing */
          } else if (eventType !== 'chat' && eventType !== 'broadcast' && participant.name) {
            void reUpdateInter?.({
              name: participant.name,
              add: true,
              average: averageLoudness,
              parameters: updatedParams,
            });
          }
        } else {
          showWaveModal.value = false;
          if (participant.name && activeSounds.includes(participant.name)) {
            activeSounds.splice(activeSounds.indexOf(participant.name), 1);
          }
          if ((shareScreenStarted || shared) && !participant.videoID) {
            /* do nothing */
          } else if (eventType !== 'chat' && eventType !== 'broadcast' && participant.name) {
            void reUpdateInter?.({
              name: participant.name,
              average: averageLoudness,
              parameters: updatedParams,
            });
          }
        }
      }

      updateActiveSounds?.(activeSounds);
    } else {
      showWaveModal.value = false;
      isMuted.value = true;
    }
  }, 2000);
};

watch(
  () => props.stream,
  (stream) => {
    setAudioSource(stream);
    if (stream) {
      startMonitoring();
    } else {
      showWaveModal.value = false;
      isMuted.value = true;
      stopMonitoring();
    }
  },
  { immediate: true }
);

watch(
  () => props.consumer,
  () => {
    if (props.stream) {
      startMonitoring();
    }
  }
);

onBeforeUnmount(() => {
  stopMonitoring();
});
</script>

<style scoped>
/* No additional styles */
</style>

// src/react-legacy/src/methods/utils/MiniAudioPlayer/MiniAudioPlayer.tsx
import React, { useEffect, useRef, useState } from "react";
import {
  ReUpdateInterType,
  UpdateParticipantAudioDecibelsType,
  ReUpdateInterParameters,
  BreakoutParticipant,
  Participant,
} from "../../../@types/types";
import { Consumer } from "mediasoup-client";

export interface MiniAudioPlayerParameters extends
    ReUpdateInterParameters {
  breakOutRoomStarted: boolean;
  breakOutRoomEnded: boolean;
  limitedBreakRoom: BreakoutParticipant[];

  // mediasfu functions
  reUpdateInter: ReUpdateInterType;
  updateParticipantAudioDecibels: UpdateParticipantAudioDecibelsType;

  getUpdatedAllParams: () => MiniAudioPlayerParameters;
  [key: string]: any;
}

export interface MiniAudioPlayerOptions {
  stream: MediaStream | null;
  remoteProducerId: string;
  consumer: Consumer;
  parameters: MiniAudioPlayerParameters;
  MiniAudioComponent?: React.ComponentType<any>;
  miniAudioProps?: Record<string, any>;
}

export type MiniAudioPlayerType = (
  options: MiniAudioPlayerOptions
) => React.JSX.Element;

/**
 * MiniAudioPlayer component is a React functional component that renders an audio player
 * and optionally a mini audio component for visualizing audio waveforms.
 *
 * @component
 * @param {MiniAudioPlayerOptions} props - The properties for the MiniAudioPlayer component.
 * @param {MediaStream | null} props.stream - The media stream to be played by the audio player.
 * @param {Consumer} props.consumer - The consumer object for the remote audio producer.
 * @param {string} props.remoteProducerId - The ID of the remote producer.
 * @param {MiniAudioPlayerParameters} props.parameters - The parameters object containing various settings and methods.
 * @param {Function} props.parameters.getUpdatedAllParams - Function to get updated parameters.
 * @param {Function} props.parameters.reUpdateInter - Function to re-update interaction parameters.
 * @param {Function} props.parameters.updateParticipantAudioDecibels - Function to update participant audio decibels.
 * @param {boolean} props.parameters.breakOutRoomStarted - Flag indicating if the breakout room has started.
 * @param {boolean} props.parameters.breakOutRoomEnded - Flag indicating if the breakout room has ended.
 * @param {Array<BreakoutParticipant>} props.parameters.limitedBreakRoom - Array of limited breakout room participants.
 * @param {React.ComponentType} [props.MiniAudioComponent] - An optional component to render for audio visualization.
 * @param {Object} [props.miniAudioProps] - Additional properties to pass to the MiniAudioComponent.
 *
 * @returns {React.JSX.Element} The rendered MiniAudioPlayer component.
 *
 * @example
 * ```tsx
 * // Import and use MiniAudioPlayer in a React component
 * import { MiniAudioPlayer } from 'mediasfu-reactjs';
 *
 * const WaveformVisualizer = ({ stream }: { stream: MediaStream }) => (
 *   <canvas width="300" height="50" />
 * );
 *
 * const App = () => {
 *   const stream = useMediaStream(); // Custom hook to get MediaStream
 *   const parameters = {
 *     // Mocked parameters with required functions
 *     getUpdatedAllParams: () => updatedParameters,
 *     reUpdateInter: () => {},
 *     updateParticipantAudioDecibels: () => {},
 *     breakOutRoomStarted: false,
 *     breakOutRoomEnded: false,
 *     limitedBreakRoom: [],
 *   };
 *
 *   return (
 *     <MiniAudioPlayer
 *       stream={stream}
 *       consumer={consumer}
 *       remoteProducerId="producer123"
 *       parameters={parameters}
 *       MiniAudioComponent={WaveformVisualizer}
 *       miniAudioProps={{ color: 'blue' }}
 *     />
 *   );
 * };
 * ```
 */

const MiniAudioPlayer: React.FC<MiniAudioPlayerOptions> = ({
  stream,
  remoteProducerId,
  consumer,
  parameters,
  MiniAudioComponent,
  miniAudioProps,
}) => {
  const { getUpdatedAllParams } = parameters;

  parameters = getUpdatedAllParams();
  let {
    reUpdateInter,
    updateParticipantAudioDecibels,
    breakOutRoomStarted,
    breakOutRoomEnded,
    limitedBreakRoom,
  } = parameters;

  const [showWaveModal, setShowWaveModal] = useState(false);
  const [isMuted, setIsMuted] = useState(false);
  const autoWaveCheck = useRef(false);

  useEffect(() => {
    if (stream) {

      let consLow = false;
      let averageLoudness = 128;

      const intervalId = setInterval(() => {
        try {
          const receiver = consumer.rtpReceiver;
          receiver?.getStats().then((stats) => {
            stats.forEach((report) => {
              if (report.type === "inbound-rtp" && report.kind === "audio" && report.audioLevel) {
                averageLoudness = 127.5 + (report.audioLevel * 127.5);
              }
            });
          });
        } catch {
          // Do nothing
        }

        const updatedParams = getUpdatedAllParams();
        let {
          eventType,
          meetingDisplayType,
          shared,
          shareScreenStarted,
          dispActiveNames,
          adminNameStream,
          participants,
          activeSounds,
          autoWave,
          updateActiveSounds,
          paginatedStreams,
          currentUserPage,
        } = updatedParams;

        const participant = participants.find(
          (obj: Participant) => obj.audioID === remoteProducerId
        );

        let audioActiveInRoom = true;
        if (participant) {
          if (breakOutRoomStarted && !breakOutRoomEnded) {
            if (
              participant.name &&
              !limitedBreakRoom
                .map((obj) => obj.name)
                .includes(participant.name)
            ) {
              audioActiveInRoom = false;
            }
          }
        }

        if (meetingDisplayType !== "video") {
          autoWaveCheck.current = true;
        }
        if (shared || shareScreenStarted) {
          autoWaveCheck.current = false;
        }

        if (participant) {
          setIsMuted(participant.muted ?? false);

          if (eventType !== "chat" && eventType !== "broadcast") {
            updateParticipantAudioDecibels({
              name: participant.name ?? "",
              averageLoudness,
              audioDecibels: updatedParams.audioDecibels,
              updateAudioDecibels: updatedParams.updateAudioDecibels,
            });
          }

          const inPage =
            paginatedStreams[currentUserPage]?.findIndex(
              (obj: any) => obj.name === participant.name
            ) ?? -1;

          if (
            participant.name &&
            !dispActiveNames.includes(participant.name) &&
            inPage == -1
          ) {
            autoWaveCheck.current = false;
            if (!adminNameStream) {
              const adminParticipant = participants.find(
                (obj: any) => obj.islevel == "2"
              );
              adminNameStream = adminParticipant ? adminParticipant.name : "";
            }

            if (participant.name == adminNameStream) {
              autoWaveCheck.current = true;
            }
          } else {
            autoWaveCheck.current = true;
          }

          if (
            participant.videoID ||
            autoWaveCheck.current ||
            (breakOutRoomStarted && !breakOutRoomEnded && audioActiveInRoom)
          ) {
            setShowWaveModal(false);

            if (averageLoudness > 127.5) {
              if (participant.name && !activeSounds.includes(participant.name)) {
                activeSounds.push(participant.name);
                consLow = false;

                if (!(shareScreenStarted || shared) || participant.videoID) {
                  if (
                    eventType !== "chat" &&
                    eventType !== "broadcast" &&
                    participant.name
                  ) {
                    reUpdateInter({
                      name: participant.name ?? "",
                      add: true,
                      average: averageLoudness,
                      parameters: updatedParams,
                    });
                  }
                }
              }
            } else {
              if (participant.name && activeSounds.includes(participant.name) && consLow) {
                activeSounds.splice(activeSounds.indexOf(participant.name), 1);
                if (!(shareScreenStarted || shared) || participant.videoID) {
                  if (
                    eventType !== "chat" &&
                    eventType !== "broadcast" &&
                    participant.name
                  ) {
                    reUpdateInter({
                      name: participant.name ?? "",
                      average: averageLoudness,
                      parameters: updatedParams,
                    });
                  }
                }
              } else {
                consLow = true;
              }
            }
          } else {
            if (averageLoudness > 127.5) {
              if (!autoWave) {
                setShowWaveModal(false);
              } else {
                setShowWaveModal(true);
              }

              if (participant.name && !activeSounds.includes(participant.name)) {
                activeSounds.push(participant.name);
              }
              if ((shareScreenStarted || shared) && !participant.videoID) {
                /* empty */
              } else {
                if (
                  eventType != "chat" &&
                  eventType != "broadcast" &&
                  participant.name
                ) {
                  reUpdateInter({
                    name: participant.name,
                    add: true,
                    average: averageLoudness,
                    parameters: updatedParams,
                  });
                }
              }
            } else {
              setShowWaveModal(false);
              if (participant.name && activeSounds.includes(participant.name)) {
                activeSounds.splice(activeSounds.indexOf(participant.name), 1);
              }
              if ((shareScreenStarted || shared) && !participant.videoID) {
                /* empty */
              } else {
                if (
                  eventType != "chat" &&
                  eventType != "broadcast" &&
                  participant.name
                ) {
                  reUpdateInter({
                    name: participant.name,
                    average: averageLoudness,
                    parameters: updatedParams,
                  });
                }
              }
            }
          }

          updateActiveSounds(activeSounds);
        } else {
          setShowWaveModal(false);
          setIsMuted(true);
        }
      }, 2000);

      return () => clearInterval(intervalId);
    }
  }, [stream]);

  const renderMiniAudioComponent = () => {
    if (MiniAudioComponent) {
      return (
        <MiniAudioComponent
          showWaveform={showWaveModal}
          visible={showWaveModal && !isMuted}
          {...miniAudioProps}
        />
      );
    }
    return null;
  };

  return (
    <div style={styles.container}>
      {stream && (
        <audio
          autoPlay
          ref={(ref) => {
            if (ref) {
              ref.srcObject = stream;
            }
          }}
        />
      )}
      {renderMiniAudioComponent()}
    </div>
  );
};

const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9,
  },
};

export default MiniAudioPlayer;
